version: 1.1.0-{build}

branches:
  only:
    - master
    - nf_sim_build
    - nf_sim_test
    - travis_build
    - /v\d*\.\d*\.\d*/


image: Visual Studio 2019

environment:
  GENERATOR: MinGW Makefiles
  PACMAN: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\

configuration: Release
platform: x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syyu python mingw-w64-x86_64-gcc"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/git"
  #- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc-fortran"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-cmake"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-doxygen"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/make"
  - yes | C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-pkg-config"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hdf5"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-libzip"
  #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-netcdf"

build_script:
  - ps: .\.appveyor\build.ps1
  - cmd: dir
  - cmd: dir \projects\vcell-solvers\build
  - cmd: dir \projects\vcell-solvers\build\bin
  
after_build:
  - cmd: \msys64\usr\bin\bash -lc "/c/projects/vcell-solvers/.appveyor/copyDependencies.sh"
  - cmd: 7z a %APPVEYOR_BUILD_FOLDER%\build\win64.zip %APPVEYOR_BUILD_FOLDER%\build\bin\*
  
artifacts:
  - path: build\win64.zip
    name: win64_archive
    
deploy:
  description: 'appveyor build for windows 64'
  provider: GitHub
  auth_token:
    secure: 4uZuKhrabKUiZTYp37aP67amqnXcGjLvDEkp8G4lv4i76sL8TIm8hE/vPC5hUOUf
  artifact: win64_archive
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true      # deploy only on tag push
