version: 1.1.0-{build}

branches:
  only:
    - master
    - nf_sim_build
    - nf_sim_test
    - travis_build
    - /v\d*\.\d*\.\d*/


image: Visual Studio 2015

environment:
  GENERATOR: MinGW Makefiles
  PACMAN: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\

configuration: Release
platform: x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syyu python mingw-w64-x86_64-gcc"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/git"
  #- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc-fortran"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-cmake"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-doxygen"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/make"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-pkg-config"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hdf5"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-libzip"
  #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-netcdf"

#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/git"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc-fortran"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-7.3.0-2-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-fortran-7.3.0-2-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -v -S mingw64/mingw-w64-x86_64-cmake"
# # install cmake and dependencies
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-c-ares-1.14.0-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-brotli-1.0.4-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libunistring-0.9.10-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libidn2-2.0.5-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libmetalink-0.1.3-3-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libssh2-1.8.0-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-jansson-2.11-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-nghttp2-1.32.0-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-curl-7.59.0-2-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-jsoncpp-1.8.4-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-lz4-1.8.2-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-lzo2-2.10-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-nettle-3.4-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libarchive-3.3.2-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libuv-1.21.0-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-rhash-1.3.6-2-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-cmake-3.11.4-2-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-doxygen"
# # install doxygen and dependencies
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-xapian-core-1~1.4.5-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-doxygen-1.8.14-2-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/make"
# # install make
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-make-4.2.1-1-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-pkg-config"
# # install pkg-config
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hdf5"
# # install hdf5 and dependencies
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-szip-2.1.1-2-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-hdf5-1.8.20-2-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-libzip"
# # install libzip and dependencies
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gnutls-3.6.2-1-any.pkg.tar.xz"
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libzip-1.5.1-1-any.pkg.tar.xz"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
# #  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-netcdf"
# # install netcdf
#   - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-netcdf-4.6.1-1-any.pkg.tar.xz"

build_script:
  - ps: .\.appveyor\build.ps1
  - cmd: dir
  - cmd: dir \projects\vcell-solvers\build
  - cmd: dir \projects\vcell-solvers\build\bin
  
after_build:
  - cmd: \msys64\usr\bin\bash -lc "/c/projects/vcell-solvers/.appveyor/copyDependencies.sh"
  - cmd: 7z a %APPVEYOR_BUILD_FOLDER%\build\win64.zip %APPVEYOR_BUILD_FOLDER%\build\bin\*
  
artifacts:
  - path: build\win64.zip
    name: win64_archive
    
deploy:
  description: 'appveyor build for windows 64'
  provider: GitHub
  auth_token:
    secure: 4uZuKhrabKUiZTYp37aP67amqnXcGjLvDEkp8G4lv4i76sL8TIm8hE/vPC5hUOUf
  artifact: win64_archive
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true      # deploy only on tag push
