name: CD

on: [push]

jobs:
  build:
    runs-on: windows-2019
  
    steps:
      - uses: msys2/setup-msys2@v2
      # setup windows 
      - name: Windows setup
        shell: powershell
        working-directory: ${{runner.workspace}}\vcell-solvers
          # Checking for msys64
        run: |
          mkdir build
          Set-Location build
          mkdir bin


