name: CD

on: [push]

jobs:
  build:
    runs-on: windows-2019
  
    steps:
      - uses: msys2/setup-msys2@v2
      # setup windows 
      - name: Windows setup
        shell: powershell
          # Checking for msys64
        run: |
          msys2 -c 'uname -a'
          cmake -version


