name: CD

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-20.04, macos-latest, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: msys2/setup-msys2@v2
      # setup windows 
      - name: Windows setup
        if: matrix.os == 'windows-2019'
        shell: powershell
          # Checking for msys64
        run: msys2 -c 'uname -a'


