name: CD

on: [push]

jobs:
  build:
    runs-on: windows-2019
  
    steps:
      - uses: msys2/setup-msys2@v2
      # setup windows 
      - name: Windows setup
        shell: powershell
        # working-directory: ${{runner.workspace}}\vcell-solvers
          # Checking for msys64
        run: |
          mkdir build
          cd build
          mkdir bin
          cmake -G "Unix Makefiles" `
              -DCMAKE_BUILD_TYPE="Release" `
              -DOPTION_TARGET_MESSAGING=OFF `
              -DOPTION_TARGET_PARALLEL=OFF `
              -DOPTION_TARGET_CHOMBO2D_SOLVER=OFF `
              -DOPTION_TARGET_CHOMBO3D_SOLVER=OFF `
              -DOPTION_TARGET_SMOLDYN_SOLVER=ON `
              -DOPTION_TARGET_FV_SOLVER=ON `
              -DOPTION_TARGET_STOCHASTIC_SOLVER=ON `
              -DOPTION_TARGET_NFSIM_SOLVER=ON `
              -DOPTION_TARGET_MOVINGBOUNDARY_SOLVER=OFF `
              -DOPTION_TARGET_SUNDIALS_SOLVER=ON `
              -DOPTION_TARGET_HY3S_SOLVERS=ON `
                ..
          make

